#!/usr/bin/env python3
import argparse
import logging
import threading
import time
import traceback
import sys

from steemvote.config import Config, ConfigError
from steemvote.monitor import Monitor

vote_interval = 30

def main():
    # Silence the piston logger.
    logger = logging.getLogger()
    logger.setLevel(logging.CRITICAL)
    # Initialize logging.
    logger = logging.getLogger('steemvote')
    ch = logging.StreamHandler()
    ch.setFormatter(logging.Formatter('%(asctime)s %(levelname)s [%(name)s] %(message)s'))
    logger.addHandler(ch)
    logger.setLevel(logging.DEBUG)

    # Command-line arguments.
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--config', type=str, default='', help='Path to config file')
    parser.add_argument('-w', '--wif', type=str, help='Private key')
    args = parser.parse_args()

    # Initialize config.
    config = Config()
    config.load(args.config)

    if args.wif:
        config.set('vote_key', args.wif)

    try:
        monitor = Monitor(config)
    except ConfigError as e:
        print(str(e))
        sys.exit(1)

    t = threading.Thread(target=monitor.run)
    last_vote = time.time()
    try:
        t.start()
        while 1:
            now = time.time()
            try:
                if now - last_vote > vote_interval:
                    monitor.vote_ready_comments()
                    last_vote = now
                else:
                    time.sleep(1)
            except Exception as e:
                logger.error(str(e))
                traceback.print_exc()

    except KeyboardInterrupt:
        logger.info('Received keyboard interrupt. Quitting.')

    monitor.stop()

if __name__ == '__main__':
    main()
